### ISSUE TITLE
Tweening Fix for 1.29.1

### ISSUE THREAD

**Issue by CodeSoftGit** [TheBlackParrot/NoteTweaks#4]
I noticed that the 1.29.1 version of this plugin does not have easings due to Beat Saber not including them pre-1.31.1. To address this, I have created a replacement for the `Easing` class with the necessary easing functions for the use case. Feel free to use this code however you like.

```csharp
#nullable disable
public static class Easing
{
    public static float OutCirc(float t)
    {
        return (float)System.Math.Sqrt(1 - (t - 1) * (t - 1));
    }

    public static float OutExpo(float t)
    {
        return t != 1 ? 1f - (float)System.Math.Pow(2, -10 * t) : 1f;
    }

    public static float InOutCubic(float t)
    {
        return t >= 0.5f ? (float)(1 - System.Math.Pow(-2 * t + 2, 3) / 2) : 4f * t * t * t;
    }
}
```

**Comment by TheBlackParrot** [comment]
Thanks! This is essentially what I was going to look into doing for 29 today lol
